<ul class="breadcrumb">
	<li>
		<i class="icon-home"></i>
		<a href="<?=$this->baseUrl();?>/admin">Trang chủ</a> 
		<i class="icon-angle-right"></i>
	</li>
	<li><?php echo $this->title;?></li>
</ul>
<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon user"></i><span class="break"></span>Thành viên</h2>
						<div class="box-icon">
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
						</div>
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>Tài khoản</th>
								  <th>Ngày tạo</th>
								  <th>Quyền hạn</th>
								  <th>Tình trạng</th>
								  <th>Chức năng</th>
							  </tr>
						  </thead>   
						  <tbody>					  
						  <?php foreach ($this->userList as $userList)
						  {?>
							<tr>
								<td><?=$userList->user_name;?></td>
								<td class="center"><?=$userList->user_name;?></td>
								<td class="center"><?=$userList->role_name;?></td>
								<td class="center">									
									   <?php
									       if($userList->del_chk==1)
									       {
									   ?>
									       <span class="label label-important">Khóa</span>
									   <?php 
									       }
									       else
									       {
									   ?>
									       <span class="label label-success">Hoạt động</span>
									   <?php
									       }?>
								</td>
								<td class="center">
								<?php 
									       if($userList->role_id!=1)
									       {
									           if($userList->del_chk==1)
									           {
									   ?>
									           <a class="btn btn-success" href="javascript:postSubmit('<?=$this->baseUrl();?>/admin/user/unlock', {uid: <?=$userList->user_id;?>});">
            										<i class="halflings-icon white lock"></i>  
            									</a>
									      <?php }
									       else 
									       {
									      ?>
            									<a class="btn btn-success" href="javascript:postSubmit('<?=$this->baseUrl();?>/admin/user/lock', {uid: <?=$userList->user_id;?>});">
            										<i class="halflings-icon white lock"></i>  
            									</a>
            								<?php 
									       }?>
            									<a class="btn btn-info" href="#">
            										<i class="halflings-icon white edit"></i>  
            									</a>
            									<a class="btn btn-danger" href="#">
            										<i class="halflings-icon white trash"></i> 
            									</a>
            							
        							   <?php 
        							       }
        									  
        						  }?>
        						  </td>
							</tr>
							
						  </tbody>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			
			