<div class="row-fluid">
				
				<div class="span3 statbox purple" onTablet="span6" onDesktop="span3">
					<div class="boxchart">5,6,7,3,5,4,3</div>
					<div class="number">854<i class="icon-arrow-up"></i></div>
					<div class="title">lượt truy cập</div>						
				</div>
				<div class="span3 statbox green" onTablet="span6" onDesktop="span3">
					<div class="boxchart">1,1,0,0,0,0,0</div>
					<div class="number">2<i class="icon-arrow-up"></i></div>
					<div class="title">bài đăng</div>
					
				</div>
				
</div>
             <div class="row-fluid">
				
				<div class="span8 widget blue" onTablet="span7" onDesktop="span8">
					
					<div id="stats-chart2"  style="height:282px" ></div>
					
				</div>
				
				<div class="sparkLineStats span4 widget green" onTablet="span5" onDesktop="span4">

                    <ul class="unstyled">
                        
                        <li><span class="sparkLineStats3"></span> 
                            Số trang xem: 
                            <span class="number">781</span>
                        </li>
                        <li><span class="sparkLineStats4"></span>
                            Trang / Người: 
                            <span class="number">2,19</span>
                        </li>
                        <li><span class="sparkLineStats5"></span>
                            Thời gian trung bình: 
                            <span class="number">00:02:58</span>
                        </li>
                        

                    </ul>
					
					<div class="clearfix"></div>

                </div><!-- End .sparkStats -->

			</div>
			
			<div class="row-fluid hideInIE8 circleStats">
				
				<div class="span2" onTablet="span4" onDesktop="span2">
                	<div class="circleStatsItemBox yellow">
						<div class="header">Khoảng trống sử dụng</div>
						<span class="percent">%</span>
						<div class="circleStat">
                    		<input type="text" value="1" class="whiteCircle" />
						</div>		
						<div class="footer">
							<span class="count">
								<span class="number">50000</span>
								<span class="unit">MB</span>
							</span>
							<span class="sep"> / </span>
							<span class="value">
								<span class="number">50000</span>
								<span class="unit">MB</span>
							</span>	
						</div>
                	</div>
				</div>

				<div class="span2" onTablet="span4" onDesktop="span2">
                	<div class="circleStatsItemBox green">
						<div class="header">Băng thông</div>
						<span class="percent">%</span>
						<div class="circleStat">
                    		<input type="text" value="44" class="whiteCircle" />
						</div>
						<div class="footer">
							<span class="count">
								<span class="number">2</span>
								<span class="unit">GB</span>
							</span>
							<span class="sep"> / </span>
							<span class="value">
								<span class="number">2</span>
								<span class="unit">GB</span>
							</span>	
						</div>
                	</div>
				</div>

				

				<div class="span2 noMargin" onTablet="span4" onDesktop="span2">
                	<div class="circleStatsItemBox pink">
						<div class="header">CPU</div>
						<span class="percent">%</span>
                    	<div class="circleStat">
                    		<input type="text" value="55" class="whiteCircle" />
						</div>
						<div class="footer">
							<span class="count">
								<span class="number">3.2</span>
								<span class="unit">GHz</span>
							</span>
							<span class="sep"> / </span>
							<span class="value">
								<span class="number">3.2</span>
								<span class="unit">GHz</span>
							</span>	
						</div>
                	</div>
				</div>

				<div class="span2" onTablet="span4" onDesktop="span2">
                	<div class="circleStatsItemBox orange">
						<div class="header">Bộ nhớ</div>
						<span class="percent">%</span>
                    	<div class="circleStat">
                    		<input type="text" value="7" class="whiteCircle" />
						</div>
						<div class="footer">
							<span class="count">
								<span class="number">64</span>
								<span class="unit">GB</span>
							</span>
							<span class="sep"> / </span>
							<span class="value">
								<span class="number">64</span>
								<span class="unit">GB</span>
							</span>	
						</div>
                	</div>
				</div>
				
				<div class="widget yellow span4 noMargin" onTablet="span12" onDesktop="span4">
					<h2><span class="glyphicons fire"><i></i></span> Server Load</h2>
					<hr>
					<div class="content">
						 <div id="serverLoad2" style="height:224px;"></div>
					</div>
				</div>			
			</div>
			
			<div class="row-fluid">	

				<a class="quick-button metro yellow span2" href="<?=$this->baseUrl();?>/admin/user/list">
					<i class="icon-group"></i>
					<p>Users</p>
					<span class="badge"><?=$this->countUser;?></span>
				</a>
				
				<a class="quick-button metro pink span2">
					<i class="icon-envelope"></i>
					<p>Tin nhắn</p>
					<span class="badge">88</span>
				</a>
				<a class="quick-button metro black span2">
					<i class="icon-calendar"></i>
					<p>Lịch</p>
				</a>
				
				<div class="clearfix"></div>
								
			</div><!--/row-->