            <div id="timeline-post">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="heading-section">
                                <h2>Giới thiệu chi tiết hơn</h2>
                                <img src="<?=$this->baseUrl();?>/public/images/under-heading.png" alt="" >
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-12">
                        	<h3>Giới thiệu chi tiết hơn</h3>
                            <p>Tôi là một deverloper</p>
                        </div>                        
                    </div>
                    
                    <div class="space50"></div>
                    
                    <div class="row">
                        <div class="col-md-2 col-sm-4">
                            <div class="timeline-thumb">
                                <div class="thumb">
                                    <img src="<?=$this->baseUrl();?>/public/images/timeline1.jpg" alt="">
                                </div>
                                <div class="overlay">
                                    <div class="timeline-caption">
                                        <a href="#"><h4>Breakfast</h4></a>
                                        <p>8:00 AM</p>
                                     </div>
                                 </div>
                             </div>
                        </div>
                        <div class="col-md-2 col-sm-4">
                            <div class="timeline-thumb">
                                <div class="thumb">
                                    <img src="<?=$this->baseUrl();?>/public/images/timeline2.jpg" alt="">
                                </div>
                                <div class="overlay">
                                    <div class="timeline-caption">
                                        <a href="#"><h4>Lunch</h4></a>
                                        <p>11:00 AM</p>
                                     </div>
                                 </div>
                             </div>
                        </div>
                        <div class="col-md-2 col-sm-4">
                            <div class="timeline-thumb">
                                <div class="thumb">
                                    <img src="<?=$this->baseUrl();?>/public/images/timeline3.jpg" alt="">
                                </div>
                                <div class="overlay">
                                    <div class="timeline-caption">
                                        <a href="#"><h4>Lunch</h4></a>
                                        <p>2:00 PM</p>
                                     </div>
                                 </div>
                             </div>
                        </div>
                        <div class="col-md-2 col-sm-4">
                            <div class="timeline-thumb">
                                <div class="thumb">
                                    <img src="<?=$this->baseUrl();?>/public/images/timeline4.jpg" alt="">
                                </div>
                                <div class="overlay">
                                    <div class="timeline-caption">
                                        <a href="#"><h4>Dinner</h4></a>
                                        <p>7:00 PM</p>
                                     </div>
                                 </div>
                             </div>
                        </div>
                        <div class="col-md-2 col-sm-4">
                            <div class="timeline-thumb">
                                <div class="thumb">
                                    <img src="<?=$this->baseUrl();?>/public/images/timeline5.jpg" alt="">
                                </div>
                                <div class="overlay">
                                    <div class="timeline-caption">
                                        <a href="#"><h4>Dinner</h4></a>
                                        <p>8:00 PM</p>
                                     </div>
                                 </div>
                             </div>
                        </div>
                        <div class="col-md-2 col-sm-4">
                            <div class="timeline-thumb">
                                <div class="thumb">
                                    <img src="<?=$this->baseUrl();?>/public/images/timeline6.jpg" alt="">
                                </div>
                                <div class="overlay">
                                    <div class="timeline-caption">
                                        <a href="#"><h4>Dinner</h4></a>
                                        <p>9:00 PM</p>
                                     </div>
                                 </div>
                             </div>
                        </div>
                    </div>
                </div>
            </div>


            