<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

<!-- templatemo 417 grill -->
<!-- 
Grill Template 
http://www.templatemo.com/preview/templatemo_417_grill 
-->
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle();?>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        
        <link rel="shortcut icon" href="<?=$this->baseUrl();?>/public/images/logo2.png">

        <link rel="stylesheet" href="<?=$this->baseUrl();?>/public/default/css/style.css">

        <link rel="stylesheet" href="<?=$this->baseUrl();?>/public/default/css/bootstrap.css">
        <link rel="stylesheet" href="<?=$this->baseUrl();?>/public/default/css/font-awesome.css">
        <link rel="stylesheet" href="<?=$this->baseUrl();?>/public/default/css/templatemo_style.css">
        <link rel="stylesheet" href="<?=$this->baseUrl();?>/public/default/css/templatemo_misc.css">
        <link rel="stylesheet" href="<?=$this->baseUrl();?>/public/default/css/flexslider.css">
        <link rel="stylesheet" href="<?=$this->baseUrl();?>/public/default/css/testimonails-slider.css">
         <link rel="stylesheet" href="<?=$this->baseUrl();?>/public/default/css/theme.css">
        <script src="<?=$this->baseUrl();?>/public/default/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
        <![endif]-->

            <header>
                <div id="top-header">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="home-account">
                                    <a href="<?=$this->baseUrl();?>/index">Trang chủ</a>
                                    <?php 
                                        if($this->isLogin)
                                        {
                                   ?>                                          
                                          <a href="<?=$this->baseUrl();?>/user">Xin chào <b style="color: #FFFFFF"><?=$this->user->other_name;?></b></a>
                                   <?php 
                                        }
                                    ?>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="cart-info">
                                    <!--      LOGIN   -->                                     
                                    <?php 
                                        if($this->isLogin)
                                        {
                                            if($this->user->role_id==1)
                                            {
                                   ?>        
                                            <a href="<?=$this->baseUrl();?>/admin/index">Admin</a>
                                         <?php
                                        }
                                    ?>                                   
                                          <a href="<?=$this->baseUrl();?>/login/logout">Logout</a>
                                   <?php 
                                        }
                                        else 
                                        {
                                    ?>
                                            <a href="<?=$this->baseUrl();?>/login">Login</a>
                                    <?php 
                                        }
                                    ?>                               
                                                                                                           
                                    <!--     END LOGIN      -->          
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="main-header">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="logo">
                                    <a href="<?=$this->baseUrl();?>"><img src="<?=$this->baseUrl();?>/public/images/logo.png" title="Grill Template" alt="Grill Website Template" ></a>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="main-menu">
                                    <ul>
                                        <li><a href="<?=$this->baseUrl();?>/index">Trang chủ</a></li>
                                        
                                        <?php 
                                        if($this->isLogin)
                                        {
                                        ?>
                                        <li><a href="<?=$this->baseUrl();?>/user">Thông tin cá nhân</a></li>                                        
                                        <?php 
                                        }?>
                                        <li><a href="<?=$this->baseUrl();?>/picture">Thư viện ảnh</a></li>
                                        <li><a href="<?=$this->baseUrl();?>/diary">Nhật ký</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="search-box">  
                                    <form name="search_form" method="get" class="search_form">
                                        <input id="search" type="text" />
                                        <input type="submit" id="search-button" />
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>