<!DOCTYPE html>
<html lang="en">
<head>
	
	<!-- start: Meta -->
	<meta charset="utf-8">
	<title>Trang quản trị hệ thống Itsme</title>
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- end: Mobile Specific -->
	
	<!-- start: CSS -->
	<link id="bootstrap-style" href="<?=$this->baseUrl();?>/public/admin/css/bootstrap.min.css" rel="stylesheet">
	<link href="<?=$this->baseUrl();?>/public/admin/css/bootstrap-responsive.min.css" rel="stylesheet">
	<link id="base-style" href="<?=$this->baseUrl();?>/public/admin/css/style.css" rel="stylesheet">
	<link id="base-style-responsive" href="<?=$this->baseUrl();?>/public/admin/css/style-responsive.css" rel="stylesheet">
	<link href='<?=$this->baseUrl();?>/public/admin/css/admin.css' rel='stylesheet' type='text/css'>
	<!-- end: CSS -->
	

	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<link id="ie-style" href="css/ie.css" rel="stylesheet">
	<![endif]-->
	
	<!--[if IE 9]>
		<link id="ie9style" href="css/ie9.css" rel="stylesheet">
	<![endif]-->
		
	<!-- start: Favicon -->
	<link rel="shortcut icon" href="img/favicon.ico">
	<!-- end: Favicon -->
	
		
		
		
</head>

<body>
		<!-- start: Header -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="<?=$this->baseUrl();?>/admin"><span>Trang quản trị Itsme</span></a>
								
				<!-- start: Header Menu -->
				<div class="nav-no-collapse header-nav">
					<ul class="nav pull-right">
						
						
						<!-- start: User Dropdown -->
						<li class="dropdown">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="halflings-icon white user"></i> <?=$this->user->other_name;?>
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu">
								<li class="dropdown-menu-title">
 									<span>Quản lý tài khoản</span>
								</li>
								<li><a href="<?=$this->baseUrl();?>/index"><i class="halflings-icon list-alt"></i>Giao diện người dùng</a></li>
								<li><a href="<?=$this->baseUrl();?>/login/logout"><i class="halflings-icon off"></i> Đăng xuất</a></li>
							</ul>
						</li>
						<!-- end: User Dropdown -->
					</ul>
				</div>
				<!-- end: Header Menu -->
				
			</div>
		</div>
	</div>
	<!-- start: Header -->
	
		<div class="container-fluid-full">
		<div class="row-fluid">
				
			<!-- start: Main Menu -->
			<div id="sidebar-left" class="span2">
				<div class="nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li><a href="<?=$this->baseUrl();?>/admin"><i class="icon-bar-chart"></i><span class="hidden-tablet"> Bảng điều khiển</span></a></li>	
						<li><a href="messages.html"><i class="icon-envelope"></i><span class="hidden-tablet"> Hộp thư</span></a></li>						
						<li>
							<a class="dropmenu" href="#"><i class="icon-folder-close-alt"></i><span class="hidden-tablet"> Quản lý</span></a>
							<ul>
								<li><a class="submenu" href="<?=$this->baseUrl();?>/admin/user/list"><i class="icon-file-alt"></i><span class="hidden-tablet"> Quản lý thành viên</span></a></li>
								<li><a class="submenu" href="submenu2.html"><i class="icon-file-alt"></i><span class="hidden-tablet"> Quản lý bài viết</span></a></li>
								<li><a class="submenu" href="submenu3.html"><i class="icon-file-alt"></i><span class="hidden-tablet"> Quản lý ảnh</span></a></li>
							</ul>	
						</li>
						
						<li><a href="calendar.html"><i class="icon-calendar"></i><span class="hidden-tablet"> Lịch</span></a></li>
					</ul>
				</div>
			</div>
			<!-- end: Main Menu -->
			
			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Thông báo!</h4>
					<p>Bạn cần có <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> vậy nên hãy bật chúng.</p>
				</div>
			</noscript>
			
			<!-- start: Content -->
			<div id="content" class="span10">   
                <!-- CONTENT -->
                    <?php echo $this->layout()->content;?>
                <!-- END CONTENT -->		

	</div><!--/.fluid-container-->
	
			<!-- end: Content -->
		</div><!--/#content.span10-->
		</div><!--/fluid-row-->
		
	
	<div class="clearfix"></div>
	
	<footer>

		<p>
			<span style="text-align:left;float:left">&copy; 2015 <a href="http://jiji262.github.io/Bootstrap_Metro_Dashboard/" alt="Bootstrap_Metro_Dashboard">Make by Trần Đức Thắng</a></span>
			
		</p>

	</footer>
	
	<!-- start: JavaScript-->

		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery-1.9.1.min.js"></script>
	<script src="<?=$this->baseUrl();?>/public/admin/js/jquery-migrate-1.0.0.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery-ui-1.10.0.custom.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.ui.touch-punch.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/modernizr.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/bootstrap.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.cookie.js"></script>
	
		<script src='<?=$this->baseUrl();?>/public/admin/js/fullcalendar.min.js'></script>
	
		<script src='<?=$this->baseUrl();?>/public/admin/js/jquery.dataTables.min.js'></script>

		<script src="<?=$this->baseUrl();?>/public/admin/js/excanvas.js"></script>
	<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.flot.js"></script>
	<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.flot.pie.js"></script>
	<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.flot.stack.js"></script>
	<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.flot.resize.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.chosen.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.uniform.min.js"></script>
		
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.cleditor.min.js"></script>
	
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.elfinder.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.raty.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.iphone.toggle.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.uploadify-3.1.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.gritter.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.imagesloaded.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.masonry.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.knob.modified.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/jquery.sparkline.min.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/counter.js"></script>
	
		<script src="<?=$this->baseUrl();?>/public/admin/js/retina.js"></script>

		<script src="<?=$this->baseUrl();?>/public/admin/js/custom.js"></script>
	<!-- end: JavaScript-->
	
</body>
</html>
