<div id="timeline-post">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="heading-section">
                    <h2>Đôi lời tâm sự</h2>
                    <img src="<?=$this->baseUrl();?>/public/images/under-heading.png" alt="" >
                </div>
            </div>
        </div>
        
        <div class="row">
        <?php foreach ($this->diary as $diary)
        {?>
            <div class="col-md-6">
            	<h3 style="color: #f78e21"><?=$diary->diary_title; ?></h3>
            	<p><img src="<?=$this->baseUrl();?>/public/images/diary/<?php if($diary->diary_img == "") { echo "noimage.jpg"; } else { echo $diary->diary_img;}?>" width = "150px" height = "150px" alt="" /></p>
                <p><?=$diary->diary_content; ?></p>
            </div>                      
             <?php 
        }?>
        </div>
        
        <div class="space50"></div>
        
        <!-- PAGINATOR -->
            <?php echo $this->paginationControl($this->diary, 'Sliding', 'diary/pagination.phtml');?>
         <!-- END PAGINATOR -->
    </div>
</div>

<div id="our-team">
    <div class="container">
    <?php if($this->isLogin){ ?>
        <?php if($this->check)
                {?>
        <div class="row">
            <div class="col-sx-12 col-md-12">
                <div class="heading-section">
                    <h2>Búc xúc cho hết vào đây</h2>
                    <img src="<?=$this->baseUrl();?>/public/images/under-heading.png" alt="" >
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sx-12 col-md-8 col-md-offset-3"> 
                <div class="message-form">
                    <form method="post" class="send-message" enctype="multipart/form-data">
                        <div class="row">
                            <div class="name col-md-4">
                                <input type="text" name="form[title]" id="form[title]" placeholder="Vấn đề gì?" />
                            </div>
                            <div class="email col-md-4">
                                <input type="file" name="form[img]" id="form[img]" />
                            </div>
                        </div>
                        <div style="margin-top: 20px;"></div>    
                        <div class="row">        
                            <div class="text col-md-8">
                                <textarea name="form[content]" class="ckeditor" id="editor1" placeholder="Nói rõ xem nào? Trút tâm sự vào đây"></textarea>
                            </div>   
                        </div>                              
                        <div class="send">
                            <button type="submit" name="form[send]" id="form[send]">Gửi</button>
                        </div>
                    </form>
                </div>
           </div>
        </div>
        <?php }?>
    <?php }?>
        
    </div>
</div>
